#=============================================================================
# Test requests for the Unprotected API
#=============================================================================


# Replace <your-api-management-service-name> with your actual API Management service name
@apimHostname = <your-api-management-service-name>.azure-api.net

###


# Operation that will call the protected API without any authentication (should fail)
GET https://{{apimHostname}}/unprotected/call-protected-api-without-authentication HTTP/1.1

###


# Operation that will call the protected API using the Credential Manager
GET https://{{apimHostname}}/unprotected/call-protected-api-using-credential-manager HTTP/1.1

###


# Operation that will call the protected API using the send-request policy with a secret
GET https://{{apimHostname}}/unprotected/call-protected-api-using-send-request-with-secret HTTP/1.1

###


# Operation that will call the protected API using the send-request policy with a certificate (client_assertion)
GET https://{{apimHostname}}/unprotected/call-protected-api-using-send-request-with-certificate HTTP/1.1

###